apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: word-dash
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: word-dash
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/part-of: word-dash
    spec:
      containers:
        - name: redis
          image: redis:8-alpine
          ports:
            - name: redis
              containerPort: 6379
          readinessProbe:
            tcpSocket:
              port: redis
          livenessProbe:
            tcpSocket:
              port: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: word-dash
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: word-dash
spec:
  selector:
    app.kubernetes.io/name: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
