apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare
data:
  config.yaml: |
    tunnel: word-dash
    credentials-file: /etc/cloudflared/credentials/credentials.json
    ingress:
      - hostname: word-dash.rasmalai.dev
        service: http://traefik.kube-system.svc.cluster.local:80
      - service: http_status:404
